version: "3.7"

services:
  miner:
    container_name: miner
    image: dockerminer:latest
    build: .
    ports:
      - "5000:5000"
    networks:
      - data
    extra_hosts:
      - "localhost:host-gateway"